### ISSUE TITLE
Complete filters

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_gpu_video_filters#18]
- [x] GPUImage3x3ConvolutionFilter
~GPUImage3x3TextureSamplingFilter~
- [x] GPUImageColorBalanceFilter
- [x] GPUImageColorInvertFilter
- [x] GPUImageColorMatrixFilter
- [ ] GPUImageDilationFilter
- [x] GPUImageDirectionalSobelEdgeDetectionFilter
- [x] GPUImageEmbossFilter
- [x] GPUImageFalseColorFilter
~GPUImageFilter~
~GPUImageFilterGroup~
- [x] GPUImageGlassSphereFilter
- [x] GPUImageKuwaharaFilter
- [x] GPUImageLaplacianFilter
- [x] GPUImageLevelsFilter
~GPUImageLookupFilter~
~GPUImageMixBlendFilter~
- [x] GPUImageNonMaximumSuppressionFilter
- [ ] GPUImageRGBDilationFilter
- [x] GPUImageSketchFilter
- [ ] GPUImageSmoothToonFilter
- [x] GPUImageSobelEdgeDetectionFilter
- [x] GPUImageSobelThresholdFilter
- [ ] GPUImageThresholdEdgeDetectionFilter
- [x] GPUImageTransformFilter
~GPUImageTwoInputFilter~
~GPUImageTwoPassFilter~
~GPUImageTwoPassTextureSamplingFilter~

**Comment by nataliiazabiiaka** [comment]
GPUImage3x3ConvolutionFilter, GPUImageColorInvertFilter, GPUImageDirectionalSobelEdgeDetectionFilter, GPUImageLaplacianFilter, GPUImageLevelsFilter, GPUImageNonMaximumSuppressionFilter, GPUImageSobelEdgeDetectionFilter, GPUImageTransformFilter - has another parameters;
GPUImageColorBalanceFilter, GPUImageKuwaharaFilter, GPUImageSketchFilter - has conditional statements;
GPUImageColorMatrixFilter, GPUImageFalseColorFilter, GPUImageGlassSphereFilter, GPUImageSobelThresholdFilter - has another final patameter except float parameter;
GPUImageDilationFilter, GPUImageEmbossFilter, GPUImageRGBDilationFilter, GPUImageSmoothToonFilter, GPUImageThresholdEdgeDetectionFilter - didn't know what to copy.
