### ISSUE TITLE
Pause video not working

### ISSUE THREAD

**Issue by YogendraAlgo** [nikolaydymura/flutter_gpu_video_filters#29]
When send pause request then it is not working.

**Comment by YogendraAlgo** [comment]
There is bug in library.
<img width="670" alt="Screenshot 2023-10-13 at 2 55 41 PM" src="https://github.com/nikolaydymura/flutter_gpu_video_filters/assets/147655821/3af7329a-fac0-4c7b-915b-cee4291eaf36">

**Comment by nikolaydymura** [comment]
@YogendraAlgo thanks a lot for report, the fix will be available in a few days

**Comment by nikolaydymura** [comment]
@YogendraAlgo try `0.0.10`
